### ISSUE TITLE
Improve property name definition

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/spec_volumetric#50]
Recommend to improve current definition:

| name | xs:QName | required | | Namespace and name of this property |

To a new definition, similar to Metadata in core spec:

| name | xs:QName | required | | Contains either the well-known name of the property, not defined in this 3MF extension, or vendor-defined property, which MUST be prefixed with a valid XML namespace name declared on the <model> element. |

**Comment by martinweismann** [comment]
| name | xs:QName | required | | Contains either the name of the property, defined in a 3MF extension specification, or the name of a vendor-defined property. Either MUST be prefixed with a valid XML namespace name declared on the \<model> element. |
