### ISSUE TITLE
Where are 3MF volumetric sample files？

### ISSUE THREAD

**Issue by Shomnipotence** [3MFConsortium/spec_volumetric#57]

**Comment by lvk88** [comment]
Hello, I am also interested in getting the 3mf volumetric sample files. Could you tell me where are they? I was looking in the 3mf sample repo, but couldn't find anything volumetric related.

**Comment by 3dJan** [comment]
Here are new examples for version 0.8 of the draft (implicit branch): [https://github.com/3MFConsortium/3mf-samples/tree/implicit/examples/volumetric ](https://github.com/3MFConsortium/3mf-samples/tree/implicit/examples/volumetric )
Keep in mind that the spec is still wip, although I won't expect major changes anymore.
