### ISSUE TITLE
Redefine tiling and filtering in a similar way as in the materials spec

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/spec_volumetric#7]
Change the definition so it is specified in the similar way as in the materials spec, so it get much clearer.
This section only to cover RGB and blending Alpha, not translucency.
Do we need contenttype as in texture2d? See loginal interpretation table in texture2d.
Does tilestyleuvw defaults to "wrap" and it is optinal as in texture2d?
Define alpha behaviour for blending: final outcome is RGB. Alpha is accumulated when blending layers, but the final alpha is ignored, and not used as translucency. Translucency would become another property.

In case to keep the formulas on how to map to image3d, I think it is better to specify as image3d coordinates normalized to [0,1] and all the mapping is in the Real space. Unless you want to add a last step from the normalized space to the voxel space which is then Z space.

**Comment by martinweismann** [comment]
@jordig100 : is there anything left to do?

**Comment by jordig100** [comment]
I think we have all covered in the 0.6.0 pre-release version.
